version: '3'
name: clown-id

networks:
  main:
    driver: bridge

services:
  postgres:
    container_name: clown-id_postgres
    image: postgres:15.3-alpine3.18
    restart: always
    networks:
      - main
    ports:
      - 5432:5432

    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    
    environment:
      - POSTGRES_DB=sberdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

