version: '3'
name: clown-id

networks:
  main:
    driver: bridge

services:
  clown-id_app:
    container_name: clown-id_app
    image: clown-id
    build: .
    restart: always
    volumes:
      - ./:/app/
    
    ports:
      - 80:80
    networks:
      - main

    depends_on:
      - clown-id_postgres

    command: /app/bin/app
    
  clown-id_postgres:
    container_name: clown-id_postgres
    image: postgres:15.3-alpine3.18
    restart: always
    networks:
      - main
    ports:
      - 5432:5432

    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    
    environment:
      - POSTGRES_DB=clown-id
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
