info:
  contact: {}
  description: Auth service for clown-devs projects
  title: Clown-ID API
  version: "0.1"
paths:
  /hello:
    get:
      description: Возвращает json "hello world"
      operationId: hello
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      summary: Тестовый эндпоинт для проверки работы автодокументации
      tags:
      - Test
  /login:
    get:
      description: Возвращает json(будет описан позже)
      operationId: auth-login
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      summary: Авторизация пользователя.
      tags:
      - Auth
swagger: "2.0"
