definitions:
  handlers.HandleLoginRequest:
    properties:
      app_id:
        example: "1"
        type: string
      client_id:
        example: "1"
        type: string
      email:
        description: either email or username should not be empty
        example: aboba@gmail.ru
        type: string
      password:
        example: qwerty123456
        type: string
      username:
        example: aboba
        type: string
    type: object
  handlers.HandleLoginResponse:
    properties:
      refresh_token:
        $ref: '#/definitions/models.RefreshToken'
    type: object
  handlers.HandleRegisterRequest:
    properties:
      email:
        example: aboba@gmail.com
        type: string
      password:
        example: aboba32
        type: string
      username:
        example: aboba
        type: string
    type: object
  handlers.HttpErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      error:
        example: something went wrong...
        type: string
    type: object
  models.RefreshToken:
    properties:
      app_id:
        example: "1"
        type: string
      client_id:
        example: "1"
        type: string
      expires_at:
        description: unixtime
        example: 1691407740
        type: integer
      token:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      user_id:
        example: "1"
        type: string
    type: object
  models.User:
    properties:
      email:
        example: aboba@gmail.com
        type: string
      id:
        example: "107"
        type: string
      username:
        example: aboba
        type: string
    type: object
info:
  contact: {}
  description: Auth service for clown-devs projects
  title: Clown-ID API
  version: "0.1"
paths:
  /login/:
    post:
      description: |-
        Необходим либо логин, либо email.
        В случае, если предоставлены оба поля приоритет будет у логина.
        Возвращает пару токенов - access и refresh токен или json с ошибкой
      operationId: auth-login
      parameters:
      - description: 'json запроса:'
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/handlers.HandleLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HandleLoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.HttpErrorResponse'
      summary: Аутентификация пользователя по логину или email и паролю
      tags:
      - Auth
  /register/:
    post:
      consumes:
      - application/json
      description: |-
        Принимает json с пользователем.
        Возвращает либо созданного пользователя либо json с ошибкой.
      operationId: auth-register
      parameters:
      - description: 'json пользователя:'
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/handlers.HandleRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.HttpErrorResponse'
      summary: Регистрация пользователя.
      tags:
      - Auth
swagger: "2.0"
